"""Add footer text to promo slider

Revision ID: 03b8c12ee63f
Revises: 85bfb715c97f
Create Date: 2026-03-31 21:53:15.195360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b8c12ee63f'
down_revision: Union[str, Sequence[str], None] = '85bfb715c97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_slider_items', sa.Column('footer_text_ru', sa.String(), nullable=True))
    op.add_column('promo_slider_items', sa.Column('footer_text_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_slider_items', 'footer_text_en')
    op.drop_column('promo_slider_items', 'footer_text_ru')
    # ### end Alembic commands ###
