"""add_months_to_transactions

Revision ID: 341f6431cb52
Revises: 9e87a5afdbf7
Create Date: 2026-02-05 16:02:35.220894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341f6431cb52'
down_revision: Union[str, Sequence[str], None] = '9e87a5afdbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'instructions')
    op.drop_column('characters', 'personality')
    op.add_column('payment_transactions', sa.Column('months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'months')
    op.add_column('characters', sa.Column('personality', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
