"""add_bilingual_appearance_location

Revision ID: 52260f036abb
Revises: 63b9d2f6ad0e
Create Date: 2026-02-11 06:39:42.731808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52260f036abb'
down_revision: Union[str, Sequence[str], None] = '63b9d2f6ad0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('appearance_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('appearance_en', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('location_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('location_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'location_en')
    op.drop_column('characters', 'location_ru')
    op.drop_column('characters', 'appearance_en')
    op.drop_column('characters', 'appearance_ru')
    # ### end Alembic commands ###
