"""remove prompt column add style columns

Revision ID: 63b9d2f6ad0e
Revises: e6e5578801e4
Create Date: 2026-02-11 04:57:35.642509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63b9d2f6ad0e'
down_revision: Union[str, Sequence[str], None] = 'e6e5578801e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('style_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('style_en', sa.Text(), nullable=True))
    op.drop_column('characters', 'description_en')
    op.drop_column('characters', 'prompt')
    op.drop_column('characters', 'translations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'style_en')
    op.drop_column('characters', 'style_ru')
    # ### end Alembic commands ###
