"""add_generation_time_to_chat_history

Revision ID: 7c5db3cee085
Revises: ffdf3646ff2a
Create Date: 2026-01-11 03:25:19.624813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5db3cee085'
down_revision: Union[str, Sequence[str], None] = 'ffdf3646ff2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование колонки перед добавлением
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('chat_history')]
    
    if 'generation_time' not in columns:
        op.add_column('chat_history', sa.Column('generation_time', sa.Integer(), nullable=True))
    
    # Проверяем существование индексов перед удалением
    indexes_before = [idx['name'] for idx in inspector.get_indexes('chat_history')]
    if 'idx_chat_history_character_name' in indexes_before:
        op.drop_index('idx_chat_history_character_name', table_name='chat_history')
    if 'idx_chat_history_session_id' in indexes_before:
        op.drop_index('idx_chat_history_session_id', table_name='chat_history')
    if 'idx_chat_history_user_id' in indexes_before:
        op.drop_index('idx_chat_history_user_id', table_name='chat_history')
    
    # Обновляем список индексов после удаления
    indexes_after = [idx['name'] for idx in inspector.get_indexes('chat_history')]
    
    # Создаем новые индексы только если их еще нет
    if 'ix_chat_history_character_name' not in indexes_after:
        op.create_index(op.f('ix_chat_history_character_name'), 'chat_history', ['character_name'], unique=False)
    if 'ix_chat_history_id' not in indexes_after:
        op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    if 'ix_chat_history_session_id' not in indexes_after:
        op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    if 'ix_chat_history_user_id' not in indexes_after:
        op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_character_name'), table_name='chat_history')
    op.create_index('idx_chat_history_user_id', 'chat_history', ['user_id'], unique=False)
    op.create_index('idx_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    op.create_index('idx_chat_history_character_name', 'chat_history', ['character_name'], unique=False)
    op.drop_column('chat_history', 'generation_time')
    # ### end Alembic commands ###
