"""add_welcome_discount_fields

Revision ID: 812173d283a9
Revises: abc456def789
Create Date: 2026-03-30 21:13:44.643834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812173d283a9'
down_revision: Union[str, Sequence[str], None] = 'abc456def789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Помощник для проверки колонок
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # 1. Обработка character_available_tags (slug)
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('character_available_tags')]
    if 'ix_character_available_tags_slug' in existing_indexes:
        op.drop_index('ix_character_available_tags_slug', table_name='character_available_tags')
    op.create_index(op.f('ix_character_available_tags_slug'), 'character_available_tags', ['slug'], unique=True)
    
    # 2. Обработка foreign key
    try:
        op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    except Exception:
        pass
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    
    # 3. Обработка колонок в users
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'has_welcome_discount' not in user_columns:
        op.add_column('users', sa.Column('has_welcome_discount', sa.Boolean(), nullable=False, server_default='false'))
    
    if 'welcome_discount_used' not in user_columns:
        op.add_column('users', sa.Column('welcome_discount_used', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_discount_used')
    op.drop_column('users', 'has_welcome_discount')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_character_available_tags_slug'), table_name='character_available_tags')
    op.create_index(op.f('ix_character_available_tags_slug'), 'character_available_tags', ['slug'], unique=False)
    # ### end Alembic commands ###
