"""add personality and instructions to characters

Revision ID: 814bdf670c72
Revises: 4c28f296d5f3
Create Date: 2026-02-04 04:42:20.544215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.chat_bot.models.models
import app.models.subscription

# revision identifiers, used by Alembic.
revision: str = '814bdf670c72'
down_revision: Union[str, Sequence[str], None] = '4c28f296d5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Cleanup Django/Token tables using raw SQL with IF EXISTS to avoid transaction abortion
    django_cleanup_sql = [
        "DROP INDEX IF EXISTS token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like",
        "DROP INDEX IF EXISTS token_blacklist_outstandingtoken_user_id_83bc629a",
        "DROP TABLE IF EXISTS token_blacklist_blacklistedtoken CASCADE",
        "DROP TABLE IF EXISTS token_blacklist_outstandingtoken CASCADE",
        "DROP INDEX IF EXISTS django_session_expire_date_a5c62663",
        "DROP INDEX IF EXISTS django_session_session_key_c0390e0f_like",
        "DROP TABLE IF EXISTS django_session CASCADE",
        "DROP TABLE IF EXISTS django_content_type CASCADE",
        "DROP TABLE IF EXISTS django_migrations CASCADE",
        "DROP INDEX IF EXISTS auth_group_permissions_group_id_b120cbf9",
        "DROP INDEX IF EXISTS auth_group_permissions_permission_id_84c5c92e",
        "DROP TABLE IF EXISTS auth_group_permissions CASCADE",
        "DROP INDEX IF EXISTS auth_group_name_a6ea08ec_like",
        "DROP TABLE IF EXISTS auth_group CASCADE",
        "DROP INDEX IF EXISTS django_admin_log_content_type_id_c4bce8eb",
        "DROP INDEX IF EXISTS django_admin_log_user_id_c564eba6",
        "DROP TABLE IF EXISTS django_admin_log CASCADE",
        "DROP INDEX IF EXISTS auth_permission_content_type_id_2f476e4b",
        "DROP TABLE IF EXISTS auth_permission CASCADE",
    ]

    for sql in django_cleanup_sql:
        op.execute(sa.text(sql))

    # Standard Alembic operations with safety for existing objects
    op.execute(sa.text("ALTER TABLE IF EXISTS character_available_tags DROP CONSTRAINT IF EXISTS uq_character_available_tags_name"))
    
    # Fully idempotent index and column operations
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_character_available_tags_id ON character_available_tags (id)"))
    op.execute(sa.text("ALTER TABLE characters ADD COLUMN IF NOT EXISTS personality TEXT"))
    op.execute(sa.text("ALTER TABLE characters ADD COLUMN IF NOT EXISTS instructions TEXT"))
    
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_gallery_user_id"))

    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_user_gallery_id ON user_gallery (id)"))
    op.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_user_gallery_user_id ON user_gallery (user_id)"))
    
    # Note: alter_column doesn't easily support IF EXISTS in raw SQL cross-DB, 
    # but since it's an enum change, we'll keep it as is or wrap in try-except if it's already done.
    # However, to be safe, we'll keep it but it might still cause issues if the sequence is messed up.
    # But usually, alter_column is more forgiving than create_index.
    op.alter_column('user_subscriptions', 'subscription_type',
               existing_type=postgresql.ENUM('BASE', 'STANDARD', 'PREMIUM', 'PRO', name='subscriptiontype'),
               type_=app.models.subscription.SubscriptionTypeDB('BASE', 'FREE', 'STANDARD', 'PREMIUM'),
               existing_nullable=False)
    
    op.execute(sa.text("DROP INDEX IF EXISTS idx_users_country"))
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_country'), 'users', ['country'], unique=False)
    op.alter_column('user_subscriptions', 'subscription_type',
               existing_type=app.models.subscription.SubscriptionTypeDB('BASE', 'FREE', 'STANDARD', 'PREMIUM'),
               type_=postgresql.ENUM('BASE', 'STANDARD', 'PREMIUM', 'PRO', name='subscriptiontype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_gallery_user_id'), table_name='user_gallery')
    op.drop_index(op.f('ix_user_gallery_id'), table_name='user_gallery')
    op.create_index(op.f('idx_user_gallery_user_id'), 'user_gallery', ['user_id'], unique=False)
    op.drop_column('characters', 'instructions')
    op.drop_column('characters', 'personality')
    op.drop_index(op.f('ix_character_available_tags_id'), table_name='character_available_tags')
    op.create_unique_constraint(op.f('uq_character_available_tags_name'), 'character_available_tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_table('token_blacklist_blacklistedtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_blacklist_outstandingtoken.id'], name=op.f('token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_blacklistedtoken_pkey')),
    sa.UniqueConstraint('token_id', name=op.f('token_blacklist_blacklistedtoken_token_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('auth_group_name_a6ea08ec_like'), 'auth_group', ['name'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    op.create_index(op.f('django_session_session_key_c0390e0f_like'), 'django_session', ['session_key'], unique=False)
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('token_blacklist_outstandingtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_outstandingtoken_pkey')),
    sa.UniqueConstraint('jti', name=op.f('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('token_blacklist_outstandingtoken_user_id_83bc629a'), 'token_blacklist_outstandingtoken', ['user_id'], unique=False)
    op.create_index(op.f('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like'), 'token_blacklist_outstandingtoken', ['jti'], unique=False)
    # ### end Alembic commands ###
