"""Add promo slider table

Revision ID: 85bfb715c97f
Revises: d7c2fb0e4d78
Create Date: 2026-03-31 21:01:51.484558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bfb715c97f'
down_revision: Union[str, Sequence[str], None] = 'd7c2fb0e4d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_slider_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('subtitle_ru', sa.String(), nullable=True),
    sa.Column('subtitle_en', sa.String(), nullable=True),
    sa.Column('button_text_ru', sa.String(), nullable=False),
    sa.Column('button_text_en', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_characters_slug'), table_name='characters')
    op.create_index(op.f('ix_characters_slug'), 'characters', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_slug'), table_name='characters')
    op.create_index(op.f('ix_characters_slug'), 'characters', ['slug'], unique=False)
    op.drop_table('promo_slider_items')
    # ### end Alembic commands ###
