"""add voice_id and voice_prompt to characters

Revision ID: ac19933eb4c6
Revises: 1a266a2c85fa
Create Date: 2026-01-20 09:37:54.677808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.chat_bot.models.models

# revision identifiers, used by Alembic.
revision: str = 'ac19933eb4c6'
down_revision: Union[str, Sequence[str], None] = '1a266a2c85fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('voice_id', sa.String(length=100), nullable=True))
    op.add_column('characters', sa.Column('voice_prompt', app.chat_bot.models.models.UTF8Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_prompt')
    op.drop_column('characters', 'voice_id')
    # ### end Alembic commands ###
