"""add_multilingual_prompts_to_image_history

Revision ID: ad8756db6afc
Revises: 52260f036abb
Create Date: 2026-02-12 17:02:50.799018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8756db6afc'
down_revision: Union[str, Sequence[str], None] = '52260f036abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generation_history', sa.Column('prompt_en', sa.Text(), nullable=True))
    op.add_column('image_generation_history', sa.Column('prompt_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_generation_history', 'prompt_ru')
    op.drop_column('image_generation_history', 'prompt_en')
    # ### end Alembic commands ###
