"""Add SEO lore columns to characters

Revision ID: d7c2fb0e4d78
Revises: 812173d283a9
Create Date: 2026-03-31 15:39:37.723966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.chat_bot.models.models


# revision identifiers, used by Alembic.
revision: str = 'd7c2fb0e4d78'
down_revision: Union[str, Sequence[str], None] = '812173d283a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('seo_lore_ru', app.chat_bot.models.models.UTF8Text(), nullable=True))
    op.add_column('characters', sa.Column('seo_lore_en', app.chat_bot.models.models.UTF8Text(), nullable=True))
    op.add_column('characters', sa.Column('seo_lore_image_url', app.chat_bot.models.models.UTF8Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'seo_lore_image_url')
    op.drop_column('characters', 'seo_lore_en')
    op.drop_column('characters', 'seo_lore_ru')
    # ### end Alembic commands ###
