"""remove voice_prompt from characters

Revision ID: da77f1653522
Revises: ac19933eb4c6
Create Date: 2026-01-20 11:28:40.421927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'da77f1653522'
down_revision: Union[str, Sequence[str], None] = 'ac19933eb4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('voice_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###
