"""Initial migration

Revision ID: e2a96dc3cea2
Revises: 
Create Date: 2025-12-30 00:58:47.354011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a96dc3cea2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('generation_time', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_character_created', 'image_generation_history', ['user_id', 'character_name', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'image_generation_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_image_generation_history_character_name'), 'image_generation_history', ['character_name'], unique=False)
    op.create_index(op.f('ix_image_generation_history_created_at'), 'image_generation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_generation_history_id'), 'image_generation_history', ['id'], unique=False)
    op.create_index(op.f('ix_image_generation_history_task_id'), 'image_generation_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_image_generation_history_user_id'), 'image_generation_history', ['user_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=255), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=True),
    sa.Column('subscription_type', sa.String(length=50), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operation_id', 'payment_transactions', ['operation_id'], unique=True)
    op.create_index('idx_user_processed', 'payment_transactions', ['user_id', 'processed'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_operation_id'), 'payment_transactions', ['operation_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('fingerprint_id', sa.String(length=255), nullable=True),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_fingerprint_id'), 'users', ['fingerprint_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_history_created_at'), 'balance_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_history_user_id'), 'balance_history', ['user_id'], unique=False)
    op.create_table('character_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_comments_character_name'), 'character_comments', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_comments_user_id'), 'character_comments', ['user_id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('character_appearance', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('main_photos', sa.Text(), nullable=True),
    sa.Column('is_nsfw', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('generation_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_character_name'), 'chat_history', ['character_name'], unique=False)
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('email_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('code_type', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paid_album_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=200), nullable=False),
    sa.Column('character_slug', sa.String(length=200), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_slug', name='uq_paid_album_unlock_user_character')
    )
    op.create_index(op.f('ix_paid_album_unlocks_character_slug'), 'paid_album_unlocks', ['character_slug'], unique=False)
    op.create_index(op.f('ix_paid_album_unlocks_id'), 'paid_album_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_paid_album_unlocks_user_id'), 'paid_album_unlocks', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gallery_id'), 'user_gallery', ['id'], unique=False)
    op.create_index(op.f('ix_user_gallery_user_id'), 'user_gallery', ['user_id'], unique=False)
    op.create_table('user_gallery_unlock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unlocker_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unlocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unlocker_id', 'target_user_id', name='unique_gallery_unlock')
    )
    op.create_index(op.f('ix_user_gallery_unlock_id'), 'user_gallery_unlock', ['id'], unique=False)
    op.create_index(op.f('ix_user_gallery_unlock_target_user_id'), 'user_gallery_unlock', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_unlock_unlocker_id'), 'user_gallery_unlock', ['unlocker_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_type', sa.Enum('BASE', 'FREE', 'STANDARD', 'PREMIUM', 'PRO', name='subscriptiontype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('monthly_photos', sa.Integer(), nullable=False),
    sa.Column('max_message_length', sa.Integer(), nullable=False),
    sa.Column('used_credits', sa.Integer(), nullable=False),
    sa.Column('used_photos', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('character_main_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'photo_id', name='uq_character_main_photo')
    )
    op.create_index(op.f('ix_character_main_photos_character_id'), 'character_main_photos', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_main_photos_id'), 'character_main_photos', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_character_id'), 'chat_sessions', ['character_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('favorite_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'character_id', name='uq_favorite_character_user_character')
    )
    op.create_index(op.f('ix_favorite_characters_character_id'), 'favorite_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_favorite_characters_id'), 'favorite_characters', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_characters_user_id'), 'favorite_characters', ['user_id'], unique=False)
    op.create_table('paid_album_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'photo_id', name='uq_paid_album_photo')
    )
    op.create_index(op.f('ix_paid_album_photos_character_id'), 'paid_album_photos', ['character_id'], unique=False)
    op.create_index(op.f('ix_paid_album_photos_id'), 'paid_album_photos', ['id'], unique=False)
    op.create_table('tip_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_messages_character_id'), 'tip_messages', ['character_id'], unique=False)
    op.create_index(op.f('ix_tip_messages_id'), 'tip_messages', ['id'], unique=False)
    op.create_index(op.f('ix_tip_messages_receiver_id'), 'tip_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_tip_messages_sender_id'), 'tip_messages', ['sender_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_tip_messages_sender_id'), table_name='tip_messages')
    op.drop_index(op.f('ix_tip_messages_receiver_id'), table_name='tip_messages')
    op.drop_index(op.f('ix_tip_messages_id'), table_name='tip_messages')
    op.drop_index(op.f('ix_tip_messages_character_id'), table_name='tip_messages')
    op.drop_table('tip_messages')
    op.drop_index(op.f('ix_paid_album_photos_id'), table_name='paid_album_photos')
    op.drop_index(op.f('ix_paid_album_photos_character_id'), table_name='paid_album_photos')
    op.drop_table('paid_album_photos')
    op.drop_index(op.f('ix_favorite_characters_user_id'), table_name='favorite_characters')
    op.drop_index(op.f('ix_favorite_characters_id'), table_name='favorite_characters')
    op.drop_index(op.f('ix_favorite_characters_character_id'), table_name='favorite_characters')
    op.drop_table('favorite_characters')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_character_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_character_main_photos_id'), table_name='character_main_photos')
    op.drop_index(op.f('ix_character_main_photos_character_id'), table_name='character_main_photos')
    op.drop_table('character_main_photos')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_gallery_unlock_unlocker_id'), table_name='user_gallery_unlock')
    op.drop_index(op.f('ix_user_gallery_unlock_target_user_id'), table_name='user_gallery_unlock')
    op.drop_index(op.f('ix_user_gallery_unlock_id'), table_name='user_gallery_unlock')
    op.drop_table('user_gallery_unlock')
    op.drop_index(op.f('ix_user_gallery_user_id'), table_name='user_gallery')
    op.drop_index(op.f('ix_user_gallery_id'), table_name='user_gallery')
    op.drop_table('user_gallery')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_paid_album_unlocks_user_id'), table_name='paid_album_unlocks')
    op.drop_index(op.f('ix_paid_album_unlocks_id'), table_name='paid_album_unlocks')
    op.drop_index(op.f('ix_paid_album_unlocks_character_slug'), table_name='paid_album_unlocks')
    op.drop_table('paid_album_unlocks')
    op.drop_table('email_verification_codes')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_character_name'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_comments_user_id'), table_name='character_comments')
    op.drop_index(op.f('ix_character_comments_character_name'), table_name='character_comments')
    op.drop_table('character_comments')
    op.drop_index(op.f('ix_balance_history_user_id'), table_name='balance_history')
    op.drop_index(op.f('ix_balance_history_created_at'), table_name='balance_history')
    op.drop_table('balance_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_fingerprint_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_operation_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index('idx_user_processed', table_name='payment_transactions')
    op.drop_index('idx_operation_id', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_image_generation_history_user_id'), table_name='image_generation_history')
    op.drop_index(op.f('ix_image_generation_history_task_id'), table_name='image_generation_history')
    op.drop_index(op.f('ix_image_generation_history_id'), table_name='image_generation_history')
    op.drop_index(op.f('ix_image_generation_history_created_at'), table_name='image_generation_history')
    op.drop_index(op.f('ix_image_generation_history_character_name'), table_name='image_generation_history')
    op.drop_index('idx_user_created', table_name='image_generation_history')
    op.drop_index('idx_user_character_created', table_name='image_generation_history')
    op.drop_table('image_generation_history')
    # ### end Alembic commands ###
