"""add_split_character_fields

Revision ID: e6e5578801e4
Revises: a992b6b2d76f
Create Date: 2026-02-11 04:23:37.779789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6e5578801e4'
down_revision: Union[str, Sequence[str], None] = 'a992b6b2d76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('personality_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('situation_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('instructions_ru', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('personality_en', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('situation_en', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('instructions_en', sa.Text(), nullable=True))
    # op.drop_column('characters', 'translations')
    # op.drop_column('characters', 'description_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('characters', 'instructions_en')
    op.drop_column('characters', 'situation_en')
    op.drop_column('characters', 'personality_en')
    op.drop_column('characters', 'instructions_ru')
    op.drop_column('characters', 'situation_ru')
    op.drop_column('characters', 'personality_ru')
    # ### end Alembic commands ###
