"""Add character_ratings table

Revision ID: ea1368fac628
Revises: 7c1c4c8a9be0
Create Date: 2026-01-04 14:36:48.983458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text, inspect

# Импортируем SubscriptionTypeDB для изменения типа колонки
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from app.models.subscription import SubscriptionTypeDB

# revision identifiers, used by Alembic.
revision: str = 'ea1368fac628'
down_revision: Union[str, Sequence[str], None] = '7c1c4c8a9be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    connection = op.get_bind()
    
    # Удаляем Django таблицы и индексы только если они существуют
    # Используем IF EXISTS для безопасности (идемпотентные миграции)
    
    # auth_group
    if 'auth_group' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS auth_group_name_a6ea08ec_like'))
        op.execute(text('DROP TABLE IF EXISTS auth_group'))
    
    # django_session
    if 'django_session' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS django_session_expire_date_a5c62663'))
        op.execute(text('DROP INDEX IF EXISTS django_session_session_key_c0390e0f_like'))
        op.execute(text('DROP TABLE IF EXISTS django_session'))
    
    # django_content_type
    if 'django_content_type' in inspector.get_table_names():
        op.execute(text('DROP TABLE IF EXISTS django_content_type'))
    
    # auth_permission
    if 'auth_permission' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS auth_permission_content_type_id_2f476e4b'))
        op.execute(text('DROP TABLE IF EXISTS auth_permission'))
    
    # django_admin_log
    if 'django_admin_log' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS django_admin_log_content_type_id_c4bce8eb'))
        op.execute(text('DROP INDEX IF EXISTS django_admin_log_user_id_c564eba6'))
        op.execute(text('DROP TABLE IF EXISTS django_admin_log'))
    
    # token_blacklist_blacklistedtoken
    if 'token_blacklist_blacklistedtoken' in inspector.get_table_names():
        op.execute(text('DROP TABLE IF EXISTS token_blacklist_blacklistedtoken'))
    
    # auth_group_permissions
    if 'auth_group_permissions' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS auth_group_permissions_group_id_b120cbf9'))
        op.execute(text('DROP INDEX IF EXISTS auth_group_permissions_permission_id_84c5c92e'))
        op.execute(text('DROP TABLE IF EXISTS auth_group_permissions'))
    
    # token_blacklist_outstandingtoken
    if 'token_blacklist_outstandingtoken' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like'))
        op.execute(text('DROP INDEX IF EXISTS token_blacklist_outstandingtoken_user_id_83bc629a'))
        op.execute(text('DROP TABLE IF EXISTS token_blacklist_outstandingtoken'))
    
    # django_migrations
    if 'django_migrations' in inspector.get_table_names():
        op.execute(text('DROP TABLE IF EXISTS django_migrations'))
    
    # Добавляем колонку generation_time только если она не существует
    if 'chat_history' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('chat_history')]
        if 'generation_time' not in columns:
            op.add_column('chat_history', sa.Column('generation_time', sa.Integer(), nullable=True))
    
    # Пересоздаем индексы для chat_history только если они не существуют
    if 'chat_history' in inspector.get_table_names():
        old_indexes = ['idx_chat_history_character_name', 'idx_chat_history_session_id', 'idx_chat_history_user_id']
        for idx_name in old_indexes:
            op.execute(text(f'DROP INDEX IF EXISTS {idx_name}'))
        
        new_indexes = [
            ('ix_chat_history_character_name', 'chat_history', ['character_name']),
            ('ix_chat_history_id', 'chat_history', ['id']),
            ('ix_chat_history_session_id', 'chat_history', ['session_id']),
            ('ix_chat_history_user_id', 'chat_history', ['user_id']),
        ]
        
        for idx_name, table_name, columns in new_indexes:
            result = connection.execute(text(f"SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{idx_name}')"))
            if not result.scalar():
                op.create_index(op.f(idx_name), table_name, columns, unique=False)
    
    # Пересоздаем индексы для user_gallery только если они не существуют
    if 'user_gallery' in inspector.get_table_names():
        op.execute(text('DROP INDEX IF EXISTS idx_user_gallery_user_id'))
        
        new_indexes = [
            ('ix_user_gallery_id', 'user_gallery', ['id']),
            ('ix_user_gallery_user_id', 'user_gallery', ['user_id']),
        ]
        
        for idx_name, table_name, columns in new_indexes:
            result = connection.execute(text(f"SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = '{idx_name}')"))
            if not result.scalar():
                op.create_index(op.f(idx_name), table_name, columns, unique=False)
    
    # Изменяем тип колонки subscription_type
    op.alter_column('user_subscriptions', 'subscription_type',
               existing_type=postgresql.ENUM('BASE', 'STANDARD', 'PREMIUM', 'PRO', name='subscriptiontype'),
               type_=SubscriptionTypeDB('BASE', 'FREE', 'STANDARD', 'PREMIUM', 'PRO'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'subscription_type',
               existing_type=SubscriptionTypeDB('BASE', 'FREE', 'STANDARD', 'PREMIUM', 'PRO'),
               type_=postgresql.ENUM('BASE', 'STANDARD', 'PREMIUM', 'PRO', name='subscriptiontype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_gallery_user_id'), table_name='user_gallery')
    op.drop_index(op.f('ix_user_gallery_id'), table_name='user_gallery')
    op.create_index(op.f('idx_user_gallery_user_id'), 'user_gallery', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_character_name'), table_name='chat_history')
    op.create_index(op.f('idx_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('idx_chat_history_character_name'), 'chat_history', ['character_name'], unique=False)
    op.drop_column('chat_history', 'generation_time')
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_migrations_pkey'))
    )
    op.create_table('token_blacklist_outstandingtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_outstandingtoken_pkey'),
    sa.UniqueConstraint('jti', name='token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('token_blacklist_outstandingtoken_user_id_83bc629a'), 'token_blacklist_outstandingtoken', ['user_id'], unique=False)
    op.create_index(op.f('token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like'), 'token_blacklist_outstandingtoken', ['jti'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_permissions_pkey')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('token_blacklist_blacklistedtoken',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_blacklist_outstandingtoken.id'], name=op.f('token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_blacklistedtoken_pkey')),
    sa.UniqueConstraint('token_id', name=op.f('token_blacklist_blacklistedtoken_token_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name=op.f('django_admin_log_action_flag_check')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_users_id'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('django_admin_log_pkey'))
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_permission_pkey')),
    sa.UniqueConstraint('content_type_id', 'codename', name=op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('django_content_type_pkey')),
    sa.UniqueConstraint('app_label', 'model', name=op.f('django_content_type_app_label_model_76bd3d3b_uniq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name=op.f('django_session_pkey'))
    )
    op.create_index(op.f('django_session_session_key_c0390e0f_like'), 'django_session', ['session_key'], unique=False)
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_group_pkey')),
    sa.UniqueConstraint('name', name=op.f('auth_group_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('auth_group_name_a6ea08ec_like'), 'auth_group', ['name'], unique=False)
    # ### end Alembic commands ###
